### ISSUE TITLE
Create Database Instance

### ISSUE THREAD

**Issue by ARMmaster17** [CS4850Group5A/VirtuDoc#2]
## Tasks
- [ ] Add database plan to `heroku.yml` manifest.
- [x] Add local variant of database to Docker Compose Stack.
- [ ] Ensure `$JDBC_DATABASE_URL` is set in local stack.
- [ ] Forward `$JDBC_DATABASE_URL` in production container.
- [ ] Set `$JDBC_DATABASE_URL` (or dynamically build through runtime script) on Heroku.
- [ ] Add documentation for manual database setup and setting `$JDBC_DATABASE_URL` environment variable in IDE.

**Comment by ARMmaster17** [comment]
Previously, it was agreed upon that we would be using MySQL. Some new information has arisen, and it is worth discussing the tradeoffs before committing to a database.

*One key thing to note is that Spring uses an ORM, so realistically there should be no difference at all with these options from the perspective of Java and JavaScript development.*

Heroku offers the following database solutions, all of which are free. In the interest of keeping everything contained inside our existing Infrastructure-as-Code, I cannot recommend connecting to and using an external service.

| Provider                             | Type                          | Row Limit | Storage Limit | Backups              | Can upgrade to HIPAA-compliant tier  |
|--------------------------------------|-------------------------------|-----------|---------------|----------------------|--------------------------------------|
| Heroku PG                            | Postgres                      | 10,000    | 1 GB          | 2                    | Yes                                  |
| JawsDB                               | MariaDB | -         | 5 MB          | 1, only good for 24H | No                                   |
| ClearDB                              | MySQL                         | -         | 5 MB          | -                    | Yes, but requires additional tooling |
| Stackhero (in beta, may lose access) | MariaDB                       | ?         | ?             | No                   | No                                   |

For purposes of this chart, MariaDB is the open source version of MySQL, and generally speaking there are no major differences between the two. For Stackhero, the service is free while it is in beta, but it is a full-blown infrastructure addon, meaning someone will need to manage the database and perform maintenance when needed.

The only alternatives on Heroku with a free tier are database systems that are not JDBC-compliant (no native Spring/Java support), and designed to tackle different problems (Redis, Kafka, MongoDB, and OBS).

My personal preference is Postgres on Heroku PG as Postgres has better migration schema support, and we get an order of magnitude more storage. Heroku PG also does free automatic updates, so everything stays secure. We also have access to backups so that when a deadline is getting close, if something breaks it's easy to revert back to the last known working version of the application with all of our data included.
